# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/Out_BRAM/Out_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Out_BRAM || ORIG_REF_NAME==Out_BRAM} -quiet] -quiet

# IP: ip/add_s_20_20_21/add_s_20_20_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_s_20_20_21 || ORIG_REF_NAME==add_s_20_20_21} -quiet] -quiet

# IP: ip/add_s_19_19_20/add_s_19_19_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_s_19_19_20 || ORIG_REF_NAME==add_s_19_19_20} -quiet] -quiet

# IP: ip/add_s_18_18_19/add_s_18_18_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_s_18_18_19 || ORIG_REF_NAME==add_s_18_18_19} -quiet] -quiet

# IP: ip/add_s_17_17_18/add_s_17_17_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_s_17_17_18 || ORIG_REF_NAME==add_s_17_17_18} -quiet] -quiet

# IP: ip/add_s_16_16_17/add_s_16_16_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_s_16_16_17 || ORIG_REF_NAME==add_s_16_16_17} -quiet] -quiet

# IP: ip/mult_s_12_5_16/mult_s_12_5_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_s_12_5_16 || ORIG_REF_NAME==mult_s_12_5_16} -quiet] -quiet

# IP: ip/add_u_19_19_20/add_u_19_19_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_u_19_19_20 || ORIG_REF_NAME==add_u_19_19_20} -quiet] -quiet

# IP: ip/mult_s_16_16_30/mult_s_16_16_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_s_16_16_30 || ORIG_REF_NAME==mult_s_16_16_30} -quiet] -quiet

# IP: ip/Seq_BRAM/Seq_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Seq_BRAM || ORIG_REF_NAME==Seq_BRAM} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_2_0/design_1_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_2_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_3_0/design_1_axi_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_3_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_Slave_for_SFR_0_1/design_1_AXI_Slave_for_SFR_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_Slave_for_SFR_0_1 || ORIG_REF_NAME==design_1_AXI_Slave_for_SFR_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_3 || ORIG_REF_NAME==design_1_auto_ds_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_4 || ORIG_REF_NAME==design_1_auto_ds_4} -quiet] -quiet

# IP: ip/syspll/syspll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==syspll || ORIG_REF_NAME==syspll} -quiet] -quiet

# IP: ip/vio/vio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: ip/clk_wiz/clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet

# XDC: ip/Out_BRAM/Out_BRAM_ooc.xdc

# XDC: ip/Seq_BRAM/Seq_BRAM_ooc.xdc

# XDC: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_3 || ORIG_REF_NAME==design_1_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_4 || ORIG_REF_NAME==design_1_auto_ds_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc

# XDC: ip/syspll/syspll_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==syspll || ORIG_REF_NAME==syspll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/syspll/syspll.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==syspll || ORIG_REF_NAME==syspll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/syspll/syspll_ooc.xdc

# XDC: ip/vio/vio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# XDC: ip/ila/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila/ila_ooc.xdc

# XDC: ip/clk_wiz/clk_wiz_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz/clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz/clk_wiz_ooc.xdc
