# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths c:/Users/Admin/Documents/Project/PSS_Searcher_v7/AXI_Slave_for_SFR/AXI_Slave_for_SFR.srcs/sources_1/new [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Ant_BRAM_1/ANT_VALUE_1.coe
add_files C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Ant_BRAM_2/ANT_VALUE_2.coe
read_verilog -library xil_defaultlib {
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/Matched_Filter.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/Out_BRAM_Ctrl.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/PSS_FSM.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/PSS_Searcher.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/PSS_Timer.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/SFR_Decoder.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/Seq_BRAM_Ctrl.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/afcdac_if.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/imports/hdl/design_1_wrapper.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/fpga_rx.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/fpga_tx.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/shift_s.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/shift_u.v
  C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Out_BRAM/Out_BRAM.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Out_BRAM/Out_BRAM_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_s_20_20_21/add_s_20_20_21.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_s_19_19_20/add_s_19_19_20.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_s_18_18_19/add_s_18_18_19.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_s_17_17_18/add_s_17_17_18.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_s_16_16_17/add_s_16_16_17.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/mult_s_12_5_16/mult_s_12_5_16.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/add_u_19_19_20/add_u_19_19_20.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/mult_s_16_16_30/mult_s_16_16_30.xci

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Seq_BRAM/Seq_BRAM.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/Seq_BRAM/Seq_BRAM_ooc.xdc]

add_files C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/vio/vio.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/vio/vio.xdc]

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/ila/ila.xci
set_property used_in_synthesis false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/ila/ila_ooc.xdc]

read_ip -quiet C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
