set_property SRC_FILE_INFO {cfile:c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll.xdc rfile:../../../HELPS_vf_pss_rev_13.srcs/sources_1/ip/syspll/syspll.xdc id:1 order:EARLY scoped_inst:syspll_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc rfile:../../../HELPS_vf_pss_rev_13.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc id:2 order:EARLY scoped_inst:clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Admin/Documents/Project/PSS_Searcher_v7/HELPS_vf_pss_rev_13/HELPS_vf_pss_rev_13.srcs/constrs_1/new/top.xdc rfile:../../../HELPS_vf_pss_rev_13.srcs/constrs_1/new/top.xdc id:3} [current_design]
current_instance syspll_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.38461
current_instance
current_instance clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.033330000000000005
current_instance
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T7       [get_ports "AFC_DAC_LDAC"]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8       [get_ports "AFC_DAC_CS"]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12      [get_ports "AFC_DAC_DIN"]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8       [get_ports "AFC_DAC_SCLK"]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH11     [get_ports "VCTCXO_CLK"]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE  [get_nets VCTCXO_CLK_IBUF_inst/O]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12      [get_ports "SPI_CS"]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6       [get_ports "SPI_DR"]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6       [get_ports "SPI_DW"]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7       [get_ports "SPI_CK"]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20      [get_ports "RPI_CS0"]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22      [get_ports "RPI_CS1"]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20      [get_ports "RPI_MISO"]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20      [get_ports "RPI_MOSI"]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19      [get_ports "RPI_CK"]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6       [get_ports "GPR[0]"]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U11      [get_ports "GPR[1]"]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11      [get_ports "GPR[2]"]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T13      [get_ports "GPR[3]"]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R13      [get_ports "GPR[4]"]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y4      [get_ports "ADC_CLK"]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC2      [get_ports "DL_RX0_I[11]"]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC1      [get_ports "DL_RX0_I[10]"]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W5      [get_ports "DL_RX0_I[9]"]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W4      [get_ports "DL_RX0_I[8]"]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC7      [get_ports "DL_RX0_I[7]"]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC6      [get_ports "DL_RX0_I[6]"]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N9      [get_ports "DL_RX0_I[5]"]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N8      [get_ports "DL_RX0_I[4]"]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M10     [get_ports "DL_RX0_I[3]"]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L10     [get_ports "DL_RX0_I[2]"]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB4      [get_ports "DL_RX0_I[1]"]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC4      [get_ports "DL_RX0_I[0]"]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB3      [get_ports "DL_RX0_Q[11]"]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC3      [get_ports "DL_RX0_Q[10]"]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W2      [get_ports "DL_RX0_Q[9]"]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W1      [get_ports "DL_RX0_Q[8]"]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8      [get_ports "DL_RX0_Q[7]"]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC8      [get_ports "DL_RX0_Q[6]"]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P11     [get_ports "DL_RX0_Q[5]"]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N11     [get_ports "DL_RX0_Q[4]"]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L16     [get_ports "DL_RX0_Q[3]"]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K16     [get_ports "DL_RX0_Q[2]"]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L15     [get_ports "DL_RX0_Q[1]"]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K15     [get_ports "DL_RX0_Q[0]"]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y2      [get_ports "DL_RX1_I[11]"]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y1      [get_ports "DL_RX1_I[10]"]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V4      [get_ports "DL_RX1_I[9]"]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V3      [get_ports "DL_RX1_I[8]"]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W7      [get_ports "DL_RX1_I[7]"]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W6      [get_ports "DL_RX1_I[6]"]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y12     [get_ports "DL_RX1_I[5]"]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12     [get_ports "DL_RX1_I[4]"]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N13     [get_ports "DL_RX1_I[3]"]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M13     [get_ports "DL_RX1_I[2]"]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M15     [get_ports "DL_RX1_I[1]"]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M14     [get_ports "DL_RX1_I[0]"]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V2      [get_ports "DL_RX1_Q[11]"]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V1      [get_ports "DL_RX1_Q[10]"]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA2      [get_ports "DL_RX1_Q[9]"]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA1      [get_ports "DL_RX1_Q[8]"]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U5      [get_ports "DL_RX1_Q[7]"]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U4      [get_ports "DL_RX1_Q[6]"]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6      [get_ports "DL_RX1_Q[5]"]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB5      [get_ports "DL_RX1_Q[4]"]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y10     [get_ports "DL_RX1_Q[3]"]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y9      [get_ports "DL_RX1_Q[2]"]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L13     [get_ports "DL_RX1_Q[1]"]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K13     [get_ports "DL_RX1_Q[0]"]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH2      [get_ports "UL_RX0_I[11]"]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ2      [get_ports "UL_RX0_I[10]"]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH4      [get_ports "UL_RX0_I[9]"]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ4      [get_ports "UL_RX0_I[8]"]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH7      [get_ports "UL_RX0_I[7]"]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH6      [get_ports "UL_RX0_I[6]"]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y8      [get_ports "UL_RX0_I[5]"]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y7      [get_ports "UL_RX0_I[4]"]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U10     [get_ports "UL_RX0_I[3]"]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T10     [get_ports "UL_RX0_I[2]"]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ6      [get_ports "UL_RX0_I[1]"]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ5      [get_ports "UL_RX0_I[0]"]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG3      [get_ports "UL_RX0_Q[11]"]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH3      [get_ports "UL_RX0_Q[10]"]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE2      [get_ports "UL_RX0_Q[9]"]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE1      [get_ports "UL_RX0_Q[8]"]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG8      [get_ports "UL_RX0_Q[7]"]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH8      [get_ports "UL_RX0_Q[6]"]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y5      [get_ports "UL_RX0_Q[5]"]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA5      [get_ports "UL_RX0_Q[4]"]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE12     [get_ports "UL_RX0_Q[3]"]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF12     [get_ports "UL_RX0_Q[2]"]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T12     [get_ports "UL_RX0_Q[1]"]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R12     [get_ports "UL_RX0_Q[0]"]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH1      [get_ports "UL_RX1_I[11]"]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ1      [get_ports "UL_RX1_I[10]"]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE3      [get_ports "UL_RX1_I[9]"]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF3      [get_ports "UL_RX1_I[8]"]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD7      [get_ports "UL_RX1_I[7]"]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD6      [get_ports "UL_RX1_I[6]"]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG10     [get_ports "UL_RX1_I[5]"]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG9      [get_ports "UL_RX1_I[4]"]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB11     [get_ports "UL_RX1_I[3]"]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB10     [get_ports "UL_RX1_I[2]"]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF11     [get_ports "UL_RX1_I[1]"]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG11     [get_ports "UL_RX1_I[0]"]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD2      [get_ports "UL_RX1_Q[11]"]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD1      [get_ports "UL_RX1_Q[10]"]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF2      [get_ports "UL_RX1_Q[9]"]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF1      [get_ports "UL_RX1_Q[8]"]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD4      [get_ports "UL_RX1_Q[7]"]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE4      [get_ports "UL_RX1_Q[6]"]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE8      [get_ports "UL_RX1_Q[5]"]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF8      [get_ports "UL_RX1_Q[4]"]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD10     [get_ports "UL_RX1_Q[3]"]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE9      [get_ports "UL_RX1_Q[2]"]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11     [get_ports "UL_RX1_Q[1]"]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA10     [get_ports "UL_RX1_Q[0]"]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14     [get_ports "DBG_LED[0]"]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13     [get_ports "DBG_LED[1]"]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13     [get_ports "DBG_LED[2]"]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14     [get_ports "DBG_LED[3]"]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15     [get_ports "DBG_LED[4]"]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13     [get_ports "DBG_LED[5]"]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14     [get_ports "DBG_LED[6]"]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL12     [get_ports "DBG_LED[7]"]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14     [get_ports "DBG_SW[0]"]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14     [get_ports "DBG_SW[1]"]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM14     [get_ports "DBG_SW[2]"]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13     [get_ports "DBG_SW[3]"]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN12     [get_ports "DBG_SW[4]"]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP12     [get_ports "DBG_SW[5]"]
set_property src_info {type:XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL13     [get_ports "DBG_SW[6]"]
set_property src_info {type:XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13     [get_ports "DBG_SW[7]"]
